name: komiko
description: "A Joke App."
publish_to: 'none'

version: 1.1.2+12

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.3
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^11.0.0
  google_fonts: ^6.2.1
  intl: any
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  cached_network_image: ^3.4.1
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  in_app_purchase: ^3.3.0
  in_app_purchase_android: ^0.5.2
  firebase_remote_config: ^5.5.0
  in_app_review: ^2.0.9
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/illustrations/
    - assets/illustrations/google_logo.webp
    - assets/jokes_import.json
    - assets/Compilations de blagues_Projet Komiko.docx
