import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:komiko/services/joke_service.dart';
import 'package:komiko/models/joke_model.dart';
import 'package:komiko/services/user_service.dart';
import 'package:komiko/generated/gen_l10n/app_localizations.dart';

class ProposeJokeScreen extends StatefulWidget {
  const ProposeJokeScreen({super.key});

  @override
  State<ProposeJokeScreen> createState() => _ProposeJokeScreenState();
}

class _ProposeJokeScreenState extends State<ProposeJokeScreen> {
  final _contentController = TextEditingController();
  final _punchlineController = TextEditingController();
  String? _selectedCategory;
  bool _isLoading = false;

  @override
  void dispose() {
    _contentController.dispose();
    _punchlineController.dispose();
    super.dispose();
  }

  Future<void> _submitJoke() async {
    final l10n = AppLocalizations.of(context)!;
    if (_contentController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(l10n.enterJokeContent)));
      return;
    }

    setState(() => _isLoading = true);
    try {
      final user = context.read<UserService>().currentUser!;
      final joke = Joke(
        id: '', // Will be generated by Firestore
        content: _contentController.text.trim(),
        punchline: _punchlineController.text.trim().isEmpty ? null : _punchlineController.text.trim(),
        category: _selectedCategory ?? l10n.catGeneral,
        authorName: user.username ?? "Utilisateur",
        authorId: user.uid,
        createdAt: DateTime.now(),
      );

      await JokeService().addJoke(joke);
      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(l10n.jokePublished)));
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString())));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    _selectedCategory ??= l10n.catGeneral;

    final List<String> categories = [
      l10n.catGeneral,
      l10n.catAnimals,
      l10n.catBelgians,
      l10n.catBlondes,
      l10n.catComputer,
      l10n.catMedicine,
      l10n.catSport,
      l10n.catToto,
      l10n.catOther
    ];

    return Scaffold(
      appBar: AppBar(
        title: Text(l10n.proposeJoke),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              l10n.proposeJoke,
              style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 24),
            DropdownButtonFormField<String>(
              value: _selectedCategory,
              decoration: InputDecoration(
                labelText: l10n.category,
                border: const OutlineInputBorder(),
              ),
              items: categories.map((c) => DropdownMenuItem(value: c, child: Text(c))).toList(),
              onChanged: (value) => setState(() => _selectedCategory = value!),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _contentController,
              maxLines: 5,
              decoration: InputDecoration(
                labelText: l10n.jokeContent,
                border: const OutlineInputBorder(),
                alignLabelWithHint: true,
              ),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _punchlineController,
              decoration: InputDecoration(
                labelText: l10n.punchline,
                border: const OutlineInputBorder(),
              ),
            ),
            const SizedBox(height: 32),
            ElevatedButton(
              onPressed: _isLoading ? null : _submitJoke,
              style: ElevatedButton.styleFrom(padding: const EdgeInsets.all(16)),
              child: _isLoading ? const CircularProgressIndicator() : Text(l10n.publish),
            ),
          ],
        ),
      ),
    );
  }
}
